#!/bin/bash
#MAKEPROJ

case $1 in

	c)
        	mkdir "$2";
		cd "$2";

		mkmake c;

		echo "#include <stdio.h>" > ${PWD##*/}.c;
		echo "#include <stdlib.h>" >> ${PWD##*/}.c;
		echo "#include <unistd.h>" >> ${PWD##*/}.c;
		echo "" >> ${PWD##*/}.c;
        	echo "int main()" >> ${PWD##*/}.c;
		echo "{" >> ${PWD##*/}.c;
		echo "	printf(\"Great success\n\");" >> ${PWD##*/}.c;
		echo "	return 0;" >> ${PWD##*/}.c;
		echo "}" >> ${PWD##*/}.c;

		echo "@Foi criado com um projeto para C@"

		;;

	java)
	   	mkdir "$2";
		cd "$2";

		mkmake java;

		echo "package ${PWD##*/};" > ${PWD##*/}.java;
        	echo "" >> ${PWD##*/}.java;
		echo "public class ${PWD##*/}" >> ${PWD##*/}.java;
		echo "{" >> ${PWD##*/}.java;
		echo "" >> ${PWD##*/}.java;
		echo "	public static void main(String[] args)" >> ${PWD##*/}.java;
		echo "	{" >> ${PWD##*/}.java;
		echo "		System.out.println(\"Great success\");" >> ${PWD##*/}.java;
		echo "	}" >> ${PWD##*/}.java;
		echo "" >> ${PWD##*/}.java;
		echo "}">> ${PWD##*/}.java;

		echo "@Foi criado um projeto para Java@"

		;;

	nodejs)
		mkdir "$2";
		cd "$2";

		mkmake nodejs;

		echo "console.log(\"Great sucess\n\")" > ${PWD##*/}.js;

		echo "@Foi criado um projeto para Nodejs@";

		;;

	prolog)

		mkdir "$2";
		cd "$2";
		mkmake prolog;
		echo "${PWD##*/}:-writeln('Great success')." > ${PWD##*/}.pl;
		echo "@Foi criado um projeto para Prolog@";
		;;

	*)
		echo "@Tipo incorreto.@";
		echo "@Tente novamente (ex.: 'mkproj c bosta' ou 'mkproj java bosta').@";

		;;

esac
